# Generated by Django 2.1.7 on 2019-02-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
