# Generated by Django 2.1.7 on 2019-02-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190222_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Please check if you want your product <em>featured</em>.'),
        ),
    ]
